# Generated by Django 4.2.1 on 2023-06-06 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes')),
                ('profile_Photo', models.FileField(blank=True, null=True, upload_to='profile_Photo')),
                ('passing_year', models.IntegerField(blank=True)),
                ('looking_for', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Remote', 'Remote')], default='Full Time', max_length=30, null=True)),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='Experience In Years')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='userSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.skill')),
                ('user_skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
